/* 全局文案字典：界面统一从这里取词（章程：文案标准、术语一致） */
export const STR = {
  appName: 'CFD-Flow 流程归档管理',

  /* 工程 */
  projectsTitle: '工程',
  newProject: '新建工程',
  projectName: '工程名称',
  projectNote: '备注（可选）',
  openProject: '打开',
  deleteProject: '删除工程',
  deleteProjectConfirm: '将删除该工程下的节点、文件登记与归档记录（不影响磁盘上的任何文件）。确定删除？',
  emptyProjects: '还没有工程',
  emptyProjectsHint: '创建第一个工程，开始记录你的调试流程',
  pendingCount: '待归档 {n} 项',

  /* 节点 */
  nodesTitle: '调试节点',
  newNode: '新建节点',
  editNode: '编辑节点',
  nodeName: '节点名称',
  nodeNote: '备注（可选）',
  nodeParent: '来源于（可选）',
  nodeParentNone: '不关联（独立节点）',
  chainView: '调试链',
  deleteNode: '删除节点',
  chainRoot: '链路起点',
  derivedFrom: '来源于',
  derivedCount: '{n} 次后续尝试',
  emptyNodes: '还没有调试节点',
  emptyNodesHint: '为第一次调试尝试创建一个节点，然后把产物文件拖拽到它上面',
  cycleError: '不能将来源设为自身或自己的下游节点，这会形成循环',
  nodeDeleteChoose: '该节点下还有文件登记，请选择处置方式：',
  nodeDeleteRemove: '一并移除登记',
  nodeDeleteMove: '转移到其他节点',
  nodeDeleteTarget: '目标节点',
  nodeDeleteSourceSafe: '磁盘上的源文件不会受到任何影响。',

  /* 登记 */
  registerPick: '选择文件',
  registerPickFolder: '选择文件夹',
  registering: '正在登记…',
  registerDone: '已登记 {n} 个文件',
  registerSkipped: '{n} 项已跳过：{reasons}',
  dropHint: '把文件或文件夹拖到具体节点上完成登记',
  emptyEntries: '该节点还没有登记文件',
  emptyEntriesHint: '从文件管理器拖拽文件到这里，或点击上方按钮选择',
  colName: '文件名',
  colSize: '大小',
  colPath: '源位置',
  colTime: '登记时间',
  removeEntry: '移除登记',
  removeEntryConfirm: '仅移除登记记录，磁盘源文件保持不变。确定移除？',
  badgeMissing: '源失效',
  badgeArchived: '已归档',
  reArchive: '再次归档',

  /* 归档 */
  archive: '归档',
  archiveTitle: '归档确认',
  archiveTarget: '归档目标目录',
  browse: '浏览…',
  archiveSummary: '共 {files} 个文件，总大小 {size}',
  archiveByNode: '按节点勾选要归档的内容（默认全选）',
  diskWarning: '目标磁盘可用空间约 {free}，小于待归档总大小 {need}，请清理空间或更换目录。',
  conflictsTitle: '目标目录存在同名文件，请选择处理方式',
  conflictSkip: '跳过',
  conflictOverwrite: '覆盖',
  conflictRename: '重命名',
  startArchive: '开始归档',
  noMissingWarn: '{n} 个登记文件源位置已失效，它们将在归档时被记为失败，建议先处理。',
  archiveProgress: '归档进度',
  phaseCopying: '正在传输',
  phaseFinishing: '正在收尾',
  cancelArchive: '取消归档',
  cancelArchiveHint: '取消后未完成的临时文件会被清理，已完成的文件保留',
  archiveResult: '归档结果',
  resultCopied: '成功 {n}',
  resultSkipped: '跳过 {n}',
  resultFailed: '失败 {n}',
  failedDetail: '失败明细',
  keepSources: '保留源文件',
  deleteSources: '删除源文件',
  deleteSourcesConfirm: '将删除 {n} 个已成功归档文件的源文件，此操作不可恢复。确定删除？',
  dispositionDone: '已删除 {n} 个源文件',
  dispositionFailed: '{n} 个源文件删除失败，详见列表',
  archiveHistory: '归档历史',
  batchStatusRunning: '进行中',
  batchStatusCompleted: '已完成',
  batchStatusCancelled: '已取消',
  batchStatusFailed: '有失败',
  emptyBatches: '还没有归档记录',
  viewResults: '明细',

  /* 通用 */
  confirm: '确定',
  cancel: '取消',
  close: '关闭',
  save: '保存',
  delete: '删除',
  loading: '加载中…',
  retry: '重试',
  back: '返回',
  loadError: '加载失败',

  /* 流程框图 */
  flowGraphTitle: '流程框图',
  createDownstream: '新建下游',
  graphEmpty: '还没有调试节点',
  graphEmptyHint: '创建节点后，这里会自动呈现调试链与产物分布',
  sharedCount: '共享 {n}',
  sharedTooltip: '共享文件：{files}',
  fitView: '适应视图',

  /* 归档流程图与预设 */
  diagramSaved: '流程图已更新至归档目录',
  diagramFailed: '流程图生成失败：{reason}（归档文件本身不受影响）',
  presetsLabel: '典型流程预设',
} as const
